name: 'Helm Push to GCS'
description: 'Push a Helm Chart to GCS'
inputs:
  chart-path:
    description: 'The relative path to the helm chart to package and push.'
    required: true
  gcs-bucket:
    description: 'The (gs://) name of the GCS bucket to push to.'
    required: true
  chart-url:
    description: 'The URL of the chart. If unset, this will infer the url from the bucket name.'
    required: false
  google-credentials:
    description: 'Base64 encoded google credentials.json file'
    required: true
outputs:
  output:
    description: 'The command output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.chart-path }}
    - ${{ inputs.gcs-bucket }}
    - ${{ inputs.google-credentials }}
    - ${{ inputs.chart-url }}
